---
- hosts: localhost
  connection: local
  # user: vagrant
  user: wesley
  sudo: true

  vars_files:
    - vars/main.yml
  # vars:
    # ansible_python_interpreter: /usr/bin/python2 # For ArchLinux

  roles:
    - geerlingguy.homebrew
    # - dev

  # tasks:
    # - include: tasks/ansible-setup.yml
