---
- name: Install Caffeine
  homebrew_cask: name=caffeine state=present

- name: Make themes directory
  shell: mkdir ~/themes
  args:
    creates: ~/themes

- name: Download base16 iterm2 themes
  git: repo=ssh://git@github.com/chriskempson/base16-iterm2.git dest=~/themes/base16-iterm2

- name: Download base16 intellij themes
  git: repo=ssh://git@github.com/adilosa/base16-idea.git dest=~/themes/base16-idea

- name: Install base16 IntelliJ themes
  # https://github.com/dave-tucker/dotfiles/blob/master/idea/osx.sh
  shell: mkdir ~/Library/Preferences/IdeaIC15/colors && cd ~/themes/base16-idea && find . -name \*.icls -exec cp {} ~/Library/Preferences/IdeaIC15/colors \;
  args:
    creates: ~/Library/Preferences/IdeaIC15/colors

- name: Install Google drive
  homebrew_cask: name=google-drive state=present

- name: Install CyberDuck
  homebrew_cask: name=cyberduck state=present

- name: Install Skype
  homebrew_cask: name=skype state=present

# TODO: Amethyst? (clib -> toggle-osx-shadows)
