---
- name: Install IntelliJ IDEA
  homebrew_cask: name=intellij-idea-ce state=present

- name: Install Java
  homebrew_cask: name=java state=present

- name: Install scala
  homebrew: name=scala state=present

- name: Install sbt
  homebrew: name=sbt state=present

- name: Install AWS command line tools
  homebrew: name=awscli state=present

- name: Install mongo
  homebrew: name=mongodb state=present

# TODO: Extract Docker role

- name: Install VirtualBox
  homebrew_cask: name=virtualbox state=present

- name: Install Docker
  homebrew: name=docker state=present

- name: Install Docker-Machine
  homebrew: name=docker-machine state=present

- name: Install Amazon ECS CLI
  homebrew: name=amazon-ecs-cli state=present

# TODO: leiningen, clojure
# TODO: tree
